### ISSUE TITLE
Write funding proposal

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#117]
## Scope

- Developing the burner wallet with LeapDAO's ecosystem-development budget shouldn't be taken for granted.
- Instead: Think of it as a small seed investment in the pDAI plasma burner-wallet to get it off the ground and fundraise independently.
- Currently there's two DAOs we specifically target for fund raising: MolochDAO and MetaCartelDAO
- In successfully raising funds from these, we can further the development of the burner-wallet but more importantly, drive adoption of LeapDAOs plasma implementation on mainnet

## Deliverables

- A funding proposal that can be used to apply for MetaCartelDAO or MolochDAO. An incomplete list of things it should feature:
  - Motivation: Why is the burner-wallet and Plasma a good combination
  - The vision: Where do we wanna go with this ultimately
  - The Milestones: What will we use the funds for specifically (e.g. create the issues for this sprint: https://github.com/leapdao/burner-wallet/milestone/3)
  - The budget: How much money will we need to complete the above mentioned milestones
  - The team: Who are we? Are we realistically capable to deliver this
  - A demo: What have we developed so far. Ideally show this very prominently and incentivize the DAO members to use it (e.g. drop them a testnet coin and prompt them to send it to a friend)

## Deliverables

The MolochDAO allows to submit proposals via links. While I think a well written document could be enough to get the funds, even better would be an interactive page with a campaign to fund us. Imagine we embed the burner-wallet as an iframe in that page and drop some testnet coins in it so that investors can directly try it.

Deliverables for this issue are hence either (depending on the ecosystem budget plan:

- A funding proposal document; or
- An interactive website

## Gain for the project

- The burner-wallet stops relying on funding from LeapDAO, LeapDAO can fully concentrate on delivering Plasma
- Funding is secured that allows to develop the burner-wallet further
- Burner-wallet drives adoption to LeapDAO's Plasma implementation
- Burner-wallet can be treated as LeapDAO's "first" customer e.g. use cases can be extracted. This will positively guide development and roadmap of LeapDAO

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 65%
bounty reviewer: name / 35%

Extra bounty for reviewer as there might be lots of back and forth.

**Comment by johba37** [comment]
timed out
