### ISSUE TITLE
Only show dollar/euro balance and don't confuse user with Cryptocurrencies

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#165]
## Scope

- Right now the LeapDAO burner-wallet is showing three balances with different assets. That's very confusing to a user not familiar with Cryptocurrencies.
- For exchanging PDAI => DAI => ETH is a frustrating and confusing process
- For simple payments among friends, knowledge about ETH, DAI or PDAI is not necessary

## Deliverables

- Make the wallet simply show a dollar balance like daicard
- For the time being, allow the user to click on an "Advanced/Debug" tab to show the various other currencies stored in the wallet. Ultimately we'd like to remove that feature though.

<img width="482" alt="Screen Shot 2019-06-21 at 14 02 24" src="https://user-images.githubusercontent.com/2758453/59921203-4d21a300-942d-11e9-9302-e348410a2e4c.png">

## Gain for the project

- Much easier usage
- Quicker off-ramping to bank account

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by MaxStalker** [comment]
Shall it be on a new branch? :)

**Comment by vrde** [comment]
I'm on it!
