### ISSUE TITLE
Use ethgasstation to predict wait times of Ethereum Mainnet transactions correctly

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#170]
## Scope

- Currently `<Loader />`'s loading times are estimated and hard coded.
- https://ethgasstation.info/json/ethgasAPI.json has an `avgWait` property however that allows us to predict how long a transaction will approximately take to confirm

## Deliverables

- Use ethgasstation to predict transaction confirmation speeds and display a correct user feedback using `<Loader />`
- Adjust `<Loader />` such that any time in milliseconds can be passed as props and the loading bar is filled in accordingly

## Gains for the project

- Less user confusion when loading finishes but transaction wasn't confirmed yet

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by MaxStalker** [comment]
Some docs can be found here:
https://docs.ethgasstation.info/

According to quick research time is specified in minutes (I might be wrong ^__^).

**Comment by MaxStalker** [comment]
Also, showing loader for more than 10 seconds is a bit strange UX. Transaction will be posted to blockchain faster, right? And then we only wait until it's gonna be confirmed.

**Comment by troggy** [comment]
FYI leap-node uses ethGasStation. May be the implementation helps: https://github.com/leapdao/leap-node/blob/master/src/utils/getRootGasPrice.js#L23
