### ISSUE TITLE
Steps to recover from failed Bity transfer

### ISSUE THREAD

**Issue by articobandurini** [leapdao/plasma-burner-wallet#176]
# Bounty

## Scope
Research and describe steps to recover from failed Bity transfer.
What if user mistakenly specify incorrect IBAN or provide not enough data?
What if access to the phone is lost, how to get a refund?
This has to be described in the Bity exchange section of the wallet, so users can take some actions in such a case.

## Deliverables
Concise block of text describing how to recover.

## Gain for the project
Clear explanation is always good in case of any unpredictable situation.

### Publicly visible delivery
PR with text in the bity off-ramping block.

## Roles
bounty gardener: @articobandurini / 10%
bounty worker: @articobandurini / 75%
bounty reviewer: @TimDaub / 15%

**Comment by articobandurini** [comment]
After conversation with Bity i've found that the process is the following:
0. Allow 2-3 days for order to complete (except weekends).
1. Check the order status on their page using the order ID: https://bity.com/orders/
2. Contact support at https://bity.com/ - chat box at the bottom right - this is the only way to contact as they don't have support email.
3. The more the user knows about what they did and observes the easier it will be for the support team to figure out what went wrong. “I used application/website X to place the order”, “I ordedered my bank to pay from account X on Monday”, “I paid with transaction X”, “My wallet/account statement does not show having received the amount” that kind of thing.

Cosnidering all above mentioned i would propose the following:
1. Show the Order ID to the user so they can use it both at the Order Status page and while talking to support.
2. Add the following explanation:
"Bity transfers usually take 1 or 2 days (weekends not included). If the money don't reach your bank account, please check the order status at https://bity.com/orders/ using your Order ID or contact Bity support team via chat at https://bity.com/".

For user's convnience we can auto-generate the order status link like this: https://bity.com/exchange/#/order/{ORDER-ID}

**Comment by TimDaub** [comment]
LGTM. Thanks @articobandurini!

Would you mind creating a ticket that makes the appropriate changes to the peep.cash wallet (if there's any required). Thanks!

**Comment by articobandurini** [comment]
Sure thing, the issue is created: #240
