### ISSUE TITLE
Opt-in and cryptographically-secured burner-wallet updates through special deployment

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#179]
## Scope

- At this point, when a user visits burner.leapdao.org the currently active index.html is fetched and all files linked within are downloaded from e.g. Cloudfront
  - These files could contains any source code as they're not content-addressed
- Additionally, PRs that are merged into master are automatically deployed to Cloudfront via Travis-CI
- This puts the burner-wallet developers into a weird position, where they could easily steal all their users' money by simply submitting malicious code in a PR
- Instead, upgrades should be opt-in and source code etc. should be content-addressed

## Deliverables
- Design a burner-wallet deployment process that e.g. deploys the whole site to IPFS
- At burner.leapdao.org, allow the user to dynamically load their preferred version
- For new users, prefer the latest version
- Give users a change log and an easy way to upgrade their wallets
- Make sure that private keys and other localStorage values are kept safe in the process

## Gains for the project
- A more secure deployment of the burner-wallet allows developers to iterate more quickly and with more piece of mind
- Users' funds are more likely to be secure

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
bounty timed out
