### ISSUE TITLE
In new wallet "Display currency" is EUR, but values are displayed as $

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#186]
## Scope

- Create a new wallet (e.g. open in incognito mode), it shows all values as $0.00 as it should
- Go to "Advanced", "EUR" is selected (it shouldn't be as value is displayed in USD ($))

## Deliverables

- Make this bug go away

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by iamonuwa** [comment]
This only happens when the currency has not been set. Try setting the currency and then create a new wallet.
