### ISSUE TITLE
Even though "Display value" is e.g. €, <Input /> is displayed in $

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#196]
## Scope

- All inputs need to read their placeholder value `$0.00` from "Display value" and apply the correct currency unit
- All inputs need to correctly convert the entered value from "Display value" to 1 DAI = 1 USD

One example:

<img width="759" alt="Screen Shot 2019-07-09 at 09 57 55" src="https://user-images.githubusercontent.com/2758453/60869918-24244f00-a230-11e9-91f8-6cd1113f5c48.png">

## Deliverables

- Complete "Display value" work such that there is no confusion for the user anymore

## Gains for the project

- Users can use the currency of their choice

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by iamonuwa** [comment]
I've fixed this issue. Sending PR for it.
