### ISSUE TITLE
Include currency into <RequestFunds /> QR Code

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#200]
## Scope

- Funds can be requested by opening the "Request" dialogue and entering an amount
- Now however, users have a choice to adjust their "Display currency"
- In some cases, users that prefer USD and users that prefer EUR could meet and try to exchange value
- The `<RequestFunds` component currently doesn't factor in the "Display currency" though, which means that if
  - a user A($) requests $1 from user B(€)
  - and B confirms this request, user B will actually send > 1$ to user A (simply said: user B will send 1€ (> 1$ currently)

## Deliverables

- Factor in the respective "Display value" of a user's wallet into "Request"
- Make sure that when two users exchange funds through "Request", that always the exact amount is sent and that the two users understand that they have different "Display values"

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johannbarbie** [comment]
should the QR code actually include the token amount? DAI in that case. then it wouldn't matter which currency i've selected. 🤔
