### ISSUE TITLE
Withdraw from privatekey is not working properly

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#216]
## Scope

- In "Advanced" => "Show PK", a user (a) can show their private key to another user (b)
- If user (b) scans user (a) private key, then they're prompted to withdraw user (a)'s side chain money
- While this functionality is implemented fully, it's currently buggy. That's annoying and leads to frustration.

## Deliverables

- Fix the above described problem

## Roles
bounty gardener: @TimDaub / 0%
bounty worker: SDP / 85%
bounty reviewer: SDP / 15%

**Comment by johannbarbie** [comment]
<img width="625" alt="Screen Shot 2019-07-12 at 7 11 06 PM" src="https://user-images.githubusercontent.com/659301/61145870-d5e5a900-a4d8-11e9-8096-59d6661832d5.png">

**Comment by TimDaub** [comment]
Too simple to claim a bounty.
