### ISSUE TITLE
Simple Balance doesn't render properly on Safari Mobile

### ISSUE THREAD

**Issue by vrde** [leapdao/plasma-burner-wallet#222]
# Bounty

## Scope
Last Saturday I tested the burner wallet with a friend and when he disabled *Advanced features* nothing was rendered anymore, he could just see the background image. Reloading the page would not work as well.

### Platform
- iOS 12.3.1
- Safari 12

### How to reproduce
- steal an iPhone
- go to https://s.peep.cash
- tap on "Advanced" at the bottom of the wallet
- disable "Advanced Features"
- tap "Done"
- **bug**: there is no UI anymore.

## Deliverables
- Make it work on Safari

## Gain for the project
- Apple users will be happy

## Publicly visible delivery
A PR.

## Roles

bounty gardener: @vrde / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

## Funded by
- EcoDev Circle (#ecosystem-development on LeapDAO Slack)

**Comment by MaxStalker** [comment]
Possible to get versions of both Safari and iOS?

**Comment by MaxStalker** [comment]
Also, did it eventually crash?
Cause that's what happens to me and if that's the case I know what's causing it.

**Comment by vrde** [comment]
> Possible to get versions of both Safari and iOS?
I've updated the issue :)

> Also, did it eventually crash?
No, it didn't.

> Cause that's what happens to me and if that's the case I know what's causing it.
Oh really? Maybe it's related then.

**Comment by TimDaub** [comment]
On my friends' iPhones (Safari), when disabling expert mode, peep.cash crashes and unfortunately is not restorable (money lost unless we update it or user can somehow fix the bug by disabling expert mode)
