### ISSUE TITLE
ExchangeRate updates are too frequent and confuse the user

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#230]
## Scope

- Currently, the `exchangeRate` is updated on every start of the burner wallet. Imagine the following scenario however:
  - You send a new user 20€. So their balance shows 20€.
  - Next time they re-open the wallet however, the price slightly dropped and now the balance is showing 19.98€. That's really annoying!

## Solution 1

- Use a Crypto/Fiat API that returns a long moving average (EMA)
- Additionally, decimals could be ignored

## Solution 2

- Keep track of the price changing but never display it to the user
- Only update the user's balance if a price change e.g. > 0.10€ happens

## Solution 3
[put yours in the comments]

## Deliverables

- Accurate balances that change as little as possible

## Gains for the project

- No confused or frustrated users that think they've "lost" money

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
bounty timed out
