### ISSUE TITLE
Tighter integration of "message"

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#233]
## Scope

<img width="746" alt="Screen Shot 2019-07-15 at 18 36 43" src="https://user-images.githubusercontent.com/2758453/61232843-8351fa00-a72f-11e9-95f3-498d216c73e8.png">

- During user testing, lots of users really liked the "message" `<Input />` field in "RequestFunds" and "SendToAddress"
- In LeapDAO's implementation, "message" is however apparently not stored anywhere and so it simply vanishes after completing a transaction

## Deliverables

- Make "message" a first-class citizen of the burner-wallet again by:
  - Storing the message in relation to every transaction in the history (`localStorage`)
  - Show the message in <RecentTransactions /> on the main screen
  - Making the "message" `<Input />` field more "sexy" (e.g. instead of
    - "optional unencrypted message" in SendToAddress.js, why not rename it to e.g. "private memo"
    - "optional unencrypted message" in RequestFunds, why not rename it to "message"
- Make sure "message" behaves as expected and remove all bugs and unexpected behavior

Inspiration:

![image](https://user-images.githubusercontent.com/2758453/61233057-f491ad00-a72f-11e9-8500-7ddf3f15e22b.png)

## Gains for the project

- Easier book keeping for the user on what they've spent money for

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
bounty timed out
