### ISSUE TITLE
History (e.g. <RecentTransactions) shouldn't be influenced by exchange rate price fluctuations

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#234]
## Scope

- Currently, when a user transfers 20€ to a friend and then the exchange rate of e.g. EUR/USD changes, then in the burner-wallet's history those 20€ can become greater or smaller than 20€

## Deliverables

- Store the exchange rate at the time of transfer in localStorage to display a fixed historical value of transfer to the user

## Gains for the project

- Users aren't confused by price fluctuations anymore

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
bounty timed out
