### ISSUE TITLE
Implement regular plasma exits in case fast exits don't work

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#235]
## Scope

- In some cases, a market maker could deny exiting funds from plasma and so a user would have to use the regular (slow) plasma exit
- [bridge-ui](https://github.com/leapdao/bridge-ui) already has this implemented

## Deliverables

- Implement slow & safe plasma exits to allow the user to exit if market makers are not available

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
bounty timed out
