### ISSUE TITLE
Displaying all decimals in "Advanced view" is unnecessary

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#237]
## Scope

See here:

![image](https://user-images.githubusercontent.com/2758453/61276296-087cf380-a7b0-11e9-97fd-c351c183a0b6.png)

- Simply to a `toFixed(2)` on those values. Nobody needs to know the > 3 decimal of ETH or DAI

## Deliverables

- Remove decimals to the second point behind the comma.

## Roles

Too easy, no bounty sorry.

**Comment by MaxStalker** [comment]
Fixed in #218
