### ISSUE TITLE
Bity off-ramping recover explanation

### ISSUE THREAD

**Issue by articobandurini** [leapdao/plasma-burner-wallet#240]
# Bounty

## Scope
According to the findings from the issue #176, do the following:

Show the Order ID to the user so they can use it both at the Bity Order Status page and while talking to their support - it has to be shown after the transaction and ideally in the list as well.

Add the following explanation after the transaction:
"Bity transfers usually take 1 or 2 days (weekends not included). If the money don't reach your bank account, please check the order status at https://bity.com/orders/ using your Order ID or contact Bity support team via chat at https://bity.com/".

For user's convnience we can auto-generate the order status link like this: https://bity.com/exchange/#/order/{ORDER-ID}

## Deliverables
Pull request with described changes.

## Gain for the project
Users have clear understanding of what to do in case of transfer failure.

### Publicly visible delivery
Block of text with links in the wallet.

## Roles
bounty gardener: @articobandurini / 10%
bounty worker: name / 75%
bounty reviewer: @articobandurini / 15%

**Comment by johba37** [comment]
bounty timed out
