### ISSUE TITLE
PDAI balance in "Receive" view can confuse users

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#249]
## Scope

- When clicking "Receive" and entering the receive screen the wallet's PDAI balance is shown
- Some users might mistake this balance with the "Requested amount" in the Request view

## Deliverables

- Modify the Receive view such that users do not get confused anymore by e.g.
  - Removing the PDAI balance from the Receive view
  - By explicitly highlighting that this is the balance and not a requested amount
  - [other options]

## Gains for the project

- Less confused users

# Roles
- Gardener: @TimDaub / 10%
- Worker: ? / 75%
- Reviewer: ? / 15%

**Comment by johba37** [comment]
bounty timed out
