### ISSUE TITLE
Extract delimiter fix from planet a

### ISSUE THREAD

**Issue by TimDaub** [leapdao/plasma-burner-wallet#254]
## Scope

- There's a fix in the Planet A repo to accept `.` and `,` as user inputs when adding floats
- https://github.com/social-dist0rtion-protocol/planet-a/pull/112

## Deliverables

- Take this fix and add it to this repo
- Add the fix to all other components too (e.g. Exchange.js)

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
bounty timed out
